"""Section renderers for report body."""

from reportlab.platypus import Paragraph, Spacer, PageBreak
from reportlab.lib.units import inch
from src.schema import ReportData, Project
from src.render.tables import create_expenditure_table, create_projects_summary_table


BOILERPLATE_TEXT = """
<b>Section 41 of the Internal Revenue Code</b><br/><br/>

Section 41 of the Internal Revenue Code provides a tax credit for increasing research activities. 
The credit is available to businesses that incur qualified research expenses (QREs) in the course of 
conducting qualified research activities.<br/><br/>

To qualify for the R&D tax credit, activities must meet the following four-part test:<br/><br/>

1. <b>Permitted Purpose:</b> The research must be undertaken to discover information that is 
technological in nature and intended to be useful in the development of a new or improved business 
component.<br/><br/>

2. <b>Elimination of Uncertainty:</b> The research must be intended to eliminate uncertainty concerning 
the development or improvement of a business component.<br/><br/>

3. <b>Process of Experimentation:</b> Substantially all of the activities must constitute a process of 
experimentation that fundamentally relies on the hard sciences (engineering, computer science, physical 
or biological sciences).<br/><br/>

4. <b>Technological in Nature:</b> The process of experimentation must fundamentally rely on principles 
of the physical or biological sciences, engineering, or computer science.<br/><br/>

Qualified research expenses include wages paid to employees performing qualified research, supplies used 
in the research process, and amounts paid to third-party contractors for qualified research services.
"""


def create_executive_summary_section(report_data: ReportData, styles: dict) -> list:
    """Create executive summary section."""
    elements = []
    
    # Section heading
    elements.append(Paragraph("1. Executive Summary", styles['Heading1']))
    elements.append(Spacer(1, 0.1 * inch))
    
    # Executive summary text (generated by NarrativeAgent)
    if report_data.executive_summary:
        # Split into paragraphs
        paragraphs = report_data.executive_summary.split('\n\n')
        for para in paragraphs:
            if para.strip():
                elements.append(Paragraph(para.strip(), styles['Body']))
    
    elements.append(Spacer(1, 0.3 * inch))
    
    # Subsection a) Summary of R&D Expenditures
    elements.append(Paragraph("a) Summary of R&D Expenditures", styles['Heading2']))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(create_expenditure_table(report_data))
    elements.append(Spacer(1, 0.3 * inch))
    
    # Subsection b) Summary of R&D Projects
    elements.append(Paragraph("b) Summary of R&D Projects", styles['Heading2']))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(create_projects_summary_table(report_data))
    elements.append(PageBreak())
    
    return elements


def create_statutory_authority_section(styles: dict) -> list:
    """Create statutory authority boilerplate section."""
    elements = []
    
    elements.append(Paragraph("2. Overview of Statutory Authority", styles['Heading1']))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(BOILERPLATE_TEXT, styles['Body']))
    elements.append(PageBreak())
    
    return elements


def create_project_analysis_section(report_data: ReportData, styles: dict) -> list:
    """Create R&D Tax Credit Analysis by Project section."""
    elements = []
    
    elements.append(Paragraph("3. R&D Tax Credit Analysis by Project", styles['Heading1']))
    elements.append(Spacer(1, 0.2 * inch))
    
    for idx, project in enumerate(report_data.projects, 1):
        elements.extend(_create_single_project_section(project, idx, styles))
    
    return elements


def _create_single_project_section(project: Project, project_num: int, styles: dict) -> list:
    """Create section for a single project."""
    elements = []
    
    # Project heading
    project_title = f"Project {project_num}: {project.project_name}"
    elements.append(Paragraph(project_title, styles['Heading2']))
    elements.append(Spacer(1, 0.1 * inch))
    
    # i) Basic Data
    elements.append(Paragraph("i) Basic Project Data", styles['Heading3']))
    basic_data = f"""
    <b>Project ID:</b> {project.project_id}<br/>
    <b>Status:</b> {project.status}<br/>
    <b>Qualified Wages:</b> ${project.qualified_wages:,.2f}<br/>
    <b>Qualified Contractors:</b> ${project.qualified_contractors:,.2f}<br/>
    <b>Qualified Supplies:</b> ${project.qualified_supplies:,.2f}<br/>
    <b>Qualified Cloud:</b> ${project.qualified_cloud:,.2f}<br/>
    <b>Federal Credit:</b> ${project.federal_credit:,.2f}
    """
    if project.man_hours:
        basic_data += f"<br/><b>Man Hours:</b> {project.man_hours:,}"
    if project.employees:
        basic_data += f"<br/><b>Employees:</b> {', '.join(project.employees)}"
    
    elements.append(Paragraph(basic_data, styles['BodyLeft']))
    elements.append(Spacer(1, 0.15 * inch))
    
    # ii) Project Description
    elements.append(Paragraph("ii) Project Description", styles['Heading3']))
    if project.project_description_narrative:
        elements.append(Paragraph(project.project_description_narrative, styles['Body']))
    elements.append(Spacer(1, 0.15 * inch))
    
    # iii) New or Improved Business Component
    elements.append(Paragraph("iii) New or Improved Business Component", styles['Heading3']))
    if project.new_improved_component:
        elements.append(Paragraph(project.new_improved_component, styles['Body']))
    elements.append(Spacer(1, 0.15 * inch))
    
    # iv) Elimination of Uncertainty
    elements.append(Paragraph("iv) Elimination of Uncertainty", styles['Heading3']))
    if project.elimination_uncertainty:
        elements.append(Paragraph(project.elimination_uncertainty, styles['Body']))
    elements.append(Spacer(1, 0.15 * inch))
    
    # v) Process of Experimentation
    elements.append(Paragraph("v) Process of Experimentation", styles['Heading3']))
    if project.process_experimentation:
        elements.append(Paragraph(project.process_experimentation, styles['Body']))
    elements.append(Spacer(1, 0.15 * inch))
    
    # vi) Technological in Nature
    elements.append(Paragraph("vi) Technological in Nature", styles['Heading3']))
    if project.technological_nature:
        elements.append(Paragraph(project.technological_nature, styles['Body']))
    elements.append(Spacer(1, 0.2 * inch))
    
    # Page break after each project (except last)
    elements.append(PageBreak())
    
    return elements
