"""Pydantic models defining the strict JSON schema for agent communication."""

from decimal import Decimal
from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator


class ReportMeta(BaseModel):
    """Metadata about the report."""
    
    client_company: str = Field(..., description="Legal name of the client company")
    years: list[int] = Field(..., description="Tax years covered in this report")
    boilerplate_version: str = Field(default="v1.0", description="Version of statutory boilerplate")


class Expenditure(BaseModel):
    """R&D expenditures for a single year."""
    
    year: int
    qualified_wages: Decimal = Field(ge=0)
    qualified_contractors: Decimal = Field(default=Decimal("0"), ge=0)
    qualified_supplies: Decimal = Field(default=Decimal("0"), ge=0)
    qualified_cloud: Decimal = Field(default=Decimal("0"), ge=0)
    total_qres: Decimal = Field(ge=0, description="Total Qualified Research Expenditures")
    federal_credit: Decimal = Field(ge=0)
    
    @field_validator("qualified_wages", "qualified_contractors", "qualified_supplies", 
                     "qualified_cloud", "total_qres", "federal_credit", mode="before")
    @classmethod
    def convert_to_decimal(cls, v):
        """Convert numeric values to Decimal for precision."""
        if v is None:
            return Decimal("0")
        return Decimal(str(v))


class ProjectFacts(BaseModel):
    """Structured facts about a project from CSV (semicolon-separated bullets)."""
    
    description_bullets: list[str] = Field(default_factory=list)
    uncertainty_bullets: list[str] = Field(default_factory=list)
    experimentation_bullets: list[str] = Field(default_factory=list)
    technology_bullets: list[str] = Field(default_factory=list)


class Project(BaseModel):
    """Individual R&D project with facts and generated narratives."""
    
    # Basic project data
    project_id: str
    project_name: str
    status: Literal["Qualified", "Non-qualified"]
    man_hours: Optional[int] = None
    employees: list[str] = Field(default_factory=list)
    
    # Financial data
    qualified_wages: Decimal = Field(ge=0)
    qualified_contractors: Decimal = Field(default=Decimal("0"), ge=0)
    qualified_supplies: Decimal = Field(default=Decimal("0"), ge=0)
    qualified_cloud: Decimal = Field(default=Decimal("0"), ge=0)
    federal_credit: Decimal = Field(ge=0)
    
    # Structured facts from CSV
    project_facts: ProjectFacts
    
    # Narratives generated by NarrativeAgent (initially None)
    executive_summary_contribution: Optional[str] = None
    project_description_narrative: Optional[str] = None
    new_improved_component: Optional[str] = None
    elimination_uncertainty: Optional[str] = None
    process_experimentation: Optional[str] = None
    technological_nature: Optional[str] = None
    
    @field_validator("qualified_wages", "qualified_contractors", "qualified_supplies",
                     "qualified_cloud", "federal_credit", mode="before")
    @classmethod
    def convert_to_decimal(cls, v):
        """Convert numeric values to Decimal for precision."""
        if v is None:
            return Decimal("0")
        return Decimal(str(v))


class ReportData(BaseModel):
    """Complete report data structure passed between agents."""
    
    report_meta: ReportMeta
    expenditures_by_year: list[Expenditure] = Field(default_factory=list)
    projects: list[Project]
    executive_summary: Optional[str] = None
    
    def get_year_range_str(self) -> str:
        """Get formatted year range string (e.g., '2022-2024' or '2023')."""
        years = sorted(self.report_meta.years)
        if len(years) == 1:
            return str(years[0])
        return f"{years[0]}-{years[-1]}"
